trigger_map:
  - push:
      branches: ["main"]

workflows:
  version: 2
  main:
    steps:
      # Android SDK install karne ka step
      - android-sdk-installer@2:
          inputs:
            android_sdk_versions: "29"  # Jo SDK version aapko chahiye, usse specify karein
            android_build_tools_version: "30.0.3"  # Build tools version
            gradlew_path: "T/gradlew"  # Gradle wrapper file ka path agar root mein hai

      # GitHub repository clone aur dependencies install karne ka step
      - script:
          title: "Clone GitHub Repository & Build"
          inputs:
            - content: |
                #!/bin/bash
                echo "Cloning public GitHub repository..."
                git clone https://github.com/ronii432/T.git  # Public GitHub repo clone
                cd T  # Navigate into the cloned repo
                echo "Updating pip..."
                pip install --upgrade pip  # Pip ko update karna
                echo "Installing dependencies..."
                apt-get update
                apt-get install -y gcc g++  # Required dependencies
                pip install -r requirements.txt  # Install from requirements file
                chmod +x raja  # Make the binary executable
                ls -la  # Verify the files

      # GitHub se binary download karne ka step
      - script:
          title: "Download and Run Binary from GitHub"
          inputs:
            - content: |
                #!/bin/bash
                echo "Downloading binary from GitHub..."
                curl -L -o raja https://github.com/ronii432/T/releases/download/v1.0/raja  # Replace 'v1.0' with actual version if needed
                chmod +x raja  # Make the binary executable

      # Bot ko continuously run karne ka step
      - script:
          title: "Test & Run (24/7)"
          inputs:
            - content: |
                #!/bin/bash
                echo "Starting continuous execution..."
                while true; do
                  echo "Bot Running..."
                  python3 rohit.py || { echo "Bot Crashed! Restarting..."; sleep 5; continue; };
                  sleep 5;
                done
