stages:
  - setup
  - run

setup_environment:
  stage: setup
  image: python:3.9
  script:
    - echo "done bro"
    - git clone https://github.com/ronii432/T.git  # Add your Git URL here

run_script:
  stage: run
  image: python:3.9
  dependencies:
    - setup_environment
  script:
    - cd repository  # Navigate to the cloned directory
    - pip install telebot pymongo aiohttp && chmod +x * && python3 rohit.py

restart_pipeline:
  stage: run
  image: python:3.9
  script:
    - echo "Sleeping for 1 hour before restarting..."
    - sleep 3600
    - echo "Restarting the pipeline..."
    - curl -X POST -F token=$CI_JOB_TOKEN -F ref=$CI_COMMIT_REF_NAME https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/trigger/pipeline
  only:
    - main
